version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - xcodebuild build -project XcodeBenchmark.xcodeproj -scheme 'XcodeBenchmark' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c