name: CI

on:
    pull_request:
        branches:
            - xcodebuild-self-hosted

jobs:
    build-and-test:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v1
        - name: Build
          run: xcodebuild -project XcodeBenchmark.xcodeproj -scheme 'XcodeBenchmark' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug build