name: CI

on:
    pull_request:
        branches:
            - bazel-self-hosted

jobs:
    build-and-test:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v1
        - name: Build
          run: bazel build //XcodeBenchmark:App

